plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6' apply false
	id 'io.spring.dependency-management' version '1.1.7' apply false
}

// 모든 서브모듈 공통 설정
subprojects {
	apply plugin: 'java'
	apply plugin: 'io.spring.dependency-management'

	group = 'com.sminoh'
	version = '0.0.1-SNAPSHOT'

	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(25)
		}
	}

	repositories {
		mavenCentral()
	}

	dependencyManagement {
		imports {
			mavenBom "org.springframework.boot:spring-boot-dependencies:4.0.6"
		}
	}

	dependencies {
		compileOnly 'org.projectlombok:lombok'
		annotationProcessor 'org.projectlombok:lombok'
		testImplementation 'org.springframework.boot:spring-boot-starter-test'
		testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

		implementation(platform('me.paulschwarz:spring-dotenv-bom:5.1.0'))
		implementation 'me.paulschwarz:springboot4-dotenv'
	}

	tasks.named('test') {
		useJUnitPlatform()
	}
}